<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<!-- This is the master version, only change this one -->
		<Version>1.7.8</Version>
		<!-- Sets the 'File description' field on the dll file -->
		<AssemblyTitle>Many customizable game balance adjustments and new features</AssemblyTitle>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="Resources\btn_switch.png" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\SVS_Detour\SVS_Detour.csproj" />
	</ItemGroup>
</Project>
